package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

/* compiled from: com.google.android.gms:play-services-ads-lite@@19.2.0 */
public final class zzaav {
    public static final zzaag<Boolean> A = zzaag.e(1, "gads:memory_bundle:debug_info", Boolean.FALSE);
    public static final zzaag<Boolean> A0 = zzaag.e(1, "gads:delay_banner_renderer:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> A1 = zzaag.e(1, "gads:enable_singleton_broadcast_receiver", Boolean.FALSE);
    public static final zzaag<Boolean> A2 = zzaag.e(1, "gads:nonagon:app_stats_lock:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> A3 = zzaag.e(1, "gads:memory_leak:b129558083", Boolean.FALSE);
    public static final zzaag<String> B = zzaag.f(1, "gads:video:codec_query_mime_types", "");
    public static final zzaag<String> B0 = zzaag.f(1, "gads:spherical_video:vertex_shader", "");
    public static final zzaag<Boolean> B1 = zzaag.e(1, "gads:native:media_view_match_parent:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> B2 = zzaag.e(1, "gads:nonagon:app_stats_main_thread:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> B3 = zzaag.e(1, "gads:unhandled_event_reporting:enabled", Boolean.FALSE);
    public static final zzaag<Integer> C = zzaag.d(1, "gads:video:codec_query_minimum_version", 16);
    public static final zzaag<String> C0 = zzaag.f(1, "gads:spherical_video:fragment_shader", "");
    public static final zzaag<Boolean> C1 = zzaag.e(1, "gads:native:count_impression_for_assets", Boolean.FALSE);
    public static final zzaag<Boolean> C2 = zzaag.e(1, "gads:uri_query_to_map_bg_thread:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> C3 = zzaag.e(1, "gads:response_info:enabled", Boolean.TRUE);
    public static final zzaag<String> D = zzaag.f(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final zzaag<Boolean> D0 = zzaag.e(1, "gads:include_local_global_rectangles", Boolean.FALSE);
    public static final zzaag<Boolean> D1 = zzaag.e(1, "gads:fluid_ad:use_wrap_content_height", Boolean.FALSE);
    public static final zzaag<Boolean> D2 = zzaag.e(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> D3 = zzaag.e(1, "gads:csi:interstitial_failed_to_show:enabled", Boolean.FALSE);
    public static final zzaag<String> E = zzaag.f(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final zzaag<Long> E0 = zzaag.k(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzaag<Long> E1 = zzaag.k(1, "gads:auto_location_timeout", 2000);
    public static final zzaag<Boolean> E2 = zzaag.e(1, "gads:active_view_gmsg_separate_pool:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> E3 = zzaag.e(1, "gads:csi:mediation_failure:enabled", Boolean.FALSE);
    public static final zzaag<String> F = zzaag.f(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final zzaag<Long> F0 = zzaag.k(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final zzaag<Boolean> F1 = zzaag.e(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> F2 = zzaag.e(1, "gads:nonagon:dpl_cancel_destroy_webview:enabled", Boolean.FALSE);
    public static final zzaag<String> F3 = zzaag.f(1, "gads:csi:error_parsing:regex", "^(\\d+)");
    public static final zzaag<String> G = zzaag.f(1, "gad:mraid:version", "3.0");
    public static final zzaag<Boolean> G0 = zzaag.e(1, "gads:position_watcher:enable_scroll_aware_ads", Boolean.FALSE);
    public static final zzaag<Boolean> G1 = zzaag.e(1, "gads:get_request_signals_cld:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> G2 = zzaag.e(1, "gads:signals:ad_id_info:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> G3 = zzaag.e(1, "gads:signal_collection_without_rendering:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> H = zzaag.e(1, "gads:mraid:expanded_interstitial_fix", Boolean.FALSE);
    public static final zzaag<Boolean> H0 = zzaag.e(1, "gads:position_watcher:send_scroll_data", Boolean.FALSE);
    public static final zzaag<Boolean> H1 = zzaag.e(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> H2 = zzaag.e(1, "gads:signals:app_index:enabled", Boolean.FALSE);
    public static final zzaag<Integer> H3 = zzaag.d(1, "gads:native_ads_signal:timeout", 1000);
    public static final zzaag<Boolean> I = zzaag.e(1, "gads:mraid:initial_size_fallback", Boolean.FALSE);
    public static final zzaag<String> I0 = zzaag.f(1, "gads:logged_adapter_version_classes", "");
    public static final zzaag<Long> I1 = zzaag.k(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzaag<Boolean> I2 = zzaag.e(1, "gads:signals:attestation_token:enabled", Boolean.FALSE);
    public static final zzaag<Integer> I3 = zzaag.d(1, "gads:signal_v2:min_version", 19677000);
    public static final zzaag<Integer> J = zzaag.d(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzaag<Long> J0 = zzaag.k(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final zzaag<Long> J1 = zzaag.k(1, "gads:parental_controls:timeout", 2000);
    public static final zzaag<Boolean> J2 = zzaag.e(1, "gads:signals:cache:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> J3 = zzaag.e(2, "DISABLE_CRASH_REPORTING", Boolean.FALSE);
    public static final zzaag<Integer> K = zzaag.d(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzaag<Boolean> K0 = zzaag.e(1, "gads:rtb_signal:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> K1 = zzaag.e(1, "gads:cache:bind_on_foreground", Boolean.FALSE);
    public static final zzaag<Boolean> K2 = zzaag.e(1, "gads:signals:doritos:v1:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> K3 = zzaag.e(1, "gads:paid_event_listener:enabled", Boolean.FALSE);
    public static final zzaag<Integer> L = zzaag.d(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzaag<Boolean> L0 = zzaag.e(1, "gads:rtb_v1_1:cld:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> L1 = zzaag.e(1, "gads:cache:bind_on_init", Boolean.FALSE);
    public static final zzaag<Boolean> L2 = zzaag.e(1, "gads:signals:location:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> L3 = zzaag.e(1, "gads:is_in_scroll_view_new_api:enabled", Boolean.TRUE);
    public static final zzaag<String> M = zzaag.f(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzaag<Boolean> M0 = zzaag.e(1, "gads:rtb_v1_1:cld:check_regex:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> M1 = zzaag.e(1, "gads:cache:bind_on_request", Boolean.FALSE);
    public static final zzaag<Boolean> M2 = zzaag.e(1, "gads:signals:parental_control:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> M3 = zzaag.e(1, "gads:native_ad_policy_validator:enabled", Boolean.TRUE);
    public static final zzaag<String> N = zzaag.f(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzaag<String> N0 = zzaag.f(1, "gads:rtb_logging:regex", "(?!)");
    public static final zzaag<Long> N1 = zzaag.k(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzaag<Boolean> N2 = zzaag.e(1, "gads:signals:video_decoder:enabled", Boolean.FALSE);
    public static final zzaag<Integer> N3 = zzaag.d(1, "gads:policy_validator_layoutparam:flags", 808);
    public static final zzaag<Boolean> O = zzaag.e(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.FALSE);
    public static final zzaag<Boolean> O0 = zzaag.e(1, "gads:v1_1:adapter_initialization:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> O1 = zzaag.e(1, "gads:cache:use_cache_data_source", Boolean.FALSE);
    public static final zzaag<Boolean> O2 = zzaag.e(1, "gads:signals:app_version_name:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> O3 = zzaag.e(2, "NATIVE_AD_DEBUGGER_ENABLED", Boolean.FALSE);
    public static final zzaag<Boolean> P = zzaag.e(1, "gads:content_fetch_enable_new_content_score", Boolean.FALSE);
    public static final zzaag<Integer> P0 = zzaag.d(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    public static final zzaag<Boolean> P1 = zzaag.e(1, "gads:cache:connection_per_read", Boolean.FALSE);
    public static final zzaag<Long> P2 = zzaag.k(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzaag<Integer> P3 = zzaag.d(1, "gads:policy_validator_overlay_margins:dp", 15);
    public static final zzaag<Boolean> Q = zzaag.e(1, "gads:content_fetch_enable_serve_once", Boolean.FALSE);
    public static final zzaag<Long> Q0 = zzaag.k(1, "gads:adapter_initialization:timeout", 30);
    public static final zzaag<Long> Q1 = zzaag.k(1, "gads:cache:connection_timeout", 5000);
    public static final zzaag<Integer> Q2 = zzaag.d(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzaag<Integer> Q3 = zzaag.d(1, "gads:policy_validator_overlay_width:dp", 350);
    public static final zzaag<Boolean> R = zzaag.e(1, "gads:sai:enabled", Boolean.TRUE);
    public static final zzaag<Long> R0 = zzaag.k(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final zzaag<Long> R1 = zzaag.k(1, "gads:cache:read_only_connection_timeout", 5000);
    public static final zzaag<Integer> R2 = zzaag.d(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
    public static final zzaag<Integer> R3 = zzaag.d(1, "gads:policy_validator_overlay_height:dp", 140);
    public static final zzaag<String> S = zzaag.f(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzaag<Boolean> S0 = zzaag.e(1, "gads:initialization_csi:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> S1 = zzaag.e(1, "gads:http_assets_cache:enabled", Boolean.FALSE);
    public static final zzaag<Integer> S2 = zzaag.d(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
    public static final zzaag<Float> S3 = zzaag.c(1, "gads:policy_validator_overlay:scale", 1.0f);
    public static final zzaag<String> T = zzaag.f(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    public static final zzaag<Boolean> T0 = zzaag.e(1, "gads:msa:experiments:enabled", Boolean.FALSE);
    public static final zzaag<String> T1 = zzaag.f(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzaag<Integer> T2 = zzaag.d(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
    public static final zzaag<Boolean> T3 = zzaag.e(1, "gads:use_wide_viewport:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> U = zzaag.e(1, "gads:sai:using_macro:enabled", Boolean.FALSE);
    public static final zzaag<Integer> U0 = zzaag.d(1, "gads:gestures:a2:enabled", 0);
    public static final zzaag<Integer> U1 = zzaag.d(1, "gads:http_assets_cache:time_out", 100);
    public static final zzaag<Boolean> U2 = zzaag.e(1, "gads:consent:shared_preference_reading:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> U3 = zzaag.e(1, "gads:load_with_overview_mode:enabled", Boolean.FALSE);
    public static final zzaag<String> V = zzaag.f(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzaag<Boolean> V0 = zzaag.e(1, "gads:gestures:clearTd:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> V1 = zzaag.e(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> V2 = zzaag.e(1, "gads:consent:iab_consent_info:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> V3 = zzaag.e(1, "gads:wire_banner_listener_after_request:enabled", Boolean.FALSE);
    public static final zzaag<Long> W = zzaag.k(1, "gads:sai:timeout_ms", -1);
    public static final zzabx<Boolean> W0 = zzacn.f5785b;
    public static final zzaag<Boolean> W1 = zzaag.e(1, "gads:chrome_custom_tabs:disabled", Boolean.FALSE);
    public static final zzaag<Boolean> W2 = zzaag.e(1, "gads:fc_consent:shared_preference_reading:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> W3 = zzaag.e(1, "gads:wire_rewarded_listener_after_request:enabled", Boolean.FALSE);
    public static final zzaag<Integer> X = zzaag.d(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzaag<Boolean> X0 = zzaag.e(1, "gads:gestures:errorlogging:enabled", Boolean.FALSE);
    public static final zzaag<Long> X1 = zzaag.k(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final zzaag<String> X2 = zzaag.f(1, "gads:sp:json_string", "");
    public static final zzaag<Boolean> X3 = zzaag.e(1, "gads:wire_app_open_listener_after_request:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> Y = zzaag.e(1, "gads:sai:app_measurement_enabled3", Boolean.FALSE);
    public static final zzaag<Long> Y0 = zzaag.k(1, "gads:gestures:task_timeout", 2000);
    public static final zzaag<String> Y1 = zzaag.f(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzaag<Boolean> Y2 = zzaag.e(1, "gads:nativeads:image:sample:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> Y3 = zzaag.e(1, "gads:wire_interstitial_listener_after_request:enabled", Boolean.FALSE);
    public static final zzaag<Integer> Z = zzaag.d(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final zzaag<Boolean> Z0 = zzaag.e(1, "gads:gestures:asig:enabled", Boolean.FALSE);
    public static final zzaag<String> Z1 = zzaag.f(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzaag<Integer> Z2 = zzaag.d(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final zzaag<Boolean> Z3 = zzaag.e(1, "gads:wire_ad_loader_listener_after_request:enabled", Boolean.FALSE);

    /* renamed from: a  reason: collision with root package name */
    public static final zzaag<String> f5713a = zzaag.f(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzaag<Boolean> a0 = zzaag.e(1, "gads:sai:force_through_reflection", Boolean.TRUE);
    public static final zzaag<Boolean> a1 = zzaag.e(1, "gads:gestures:ans:enabled", Boolean.FALSE);
    public static final zzaag<String> a2 = zzaag.f(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzaag<Boolean> a3 = zzaag.e(1, "gads:nativeads:pub_image_scale_type:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> a4 = zzaag.e(1, "gads:server_transaction_source:enabled", Boolean.FALSE);

    /* renamed from: b  reason: collision with root package name */
    public static final zzaag<String> f5714b = zzaag.f(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzaag<Boolean> b0 = zzaag.e(1, "gads:sai:gmscore_availability_check_disabled", Boolean.FALSE);
    public static final zzaag<Boolean> b1 = zzaag.e(1, "gads:gestures:tos:enabled", Boolean.FALSE);
    public static final zzaag<String> b2 = zzaag.f(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzaag<Boolean> b3 = zzaag.e(1, "gads:offline_signaling:enabled", Boolean.FALSE);
    public static final zzaag<String> b4 = zzaag.f(1, "gads:server_transaction_source:list", "Network");

    /* renamed from: c  reason: collision with root package name */
    public static final zzaag<String> f5715c = zzaag.f(1, "gads:video_exo_player:version", "3");
    public static final zzaag<Boolean> c0 = zzaag.e(1, "gads:sai:logging_disabled_for_drx", Boolean.FALSE);
    public static final zzaag<Boolean> c1 = zzaag.e(1, "gads:gestures:fpi:enabled", Boolean.FALSE);
    public static final zzaag<Integer> c2 = zzaag.d(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzaag<Integer> c3 = zzaag.d(1, "gads:offline_signaling:log_maximum", 100);
    public static final zzaag<Boolean> c4 = zzaag.e(1, "gads:can_open_app_and_open_app_action:enabled", Boolean.FALSE);

    /* renamed from: d  reason: collision with root package name */
    public static final zzaag<Integer> f5716d = zzaag.d(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzaag<Boolean> d0 = zzaag.e(1, "gads:sai:inject_firebase_proxy", Boolean.FALSE);
    public static final zzaag<Boolean> d1 = zzaag.e(1, "gads:signal:app_permissions:disabled", Boolean.FALSE);
    public static final zzaag<Integer> d2 = zzaag.d(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzaag<Boolean> d3 = zzaag.e(1, "gads:nativeads:template_signal:enabled", Boolean.TRUE);

    /* renamed from: e  reason: collision with root package name */
    public static final zzaag<Integer> f5717e = zzaag.d(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzaag<Boolean> e0 = zzaag.e(1, "gads:sai:app_measurement_npa_enabled", Boolean.FALSE);
    public static final zzaag<Boolean> e1 = zzaag.e(1, "gads:gestures:inthex:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> e2 = zzaag.e(1, "gad:interstitial_for_multi_window", Boolean.FALSE);
    public static final zzaag<Boolean> e3 = zzaag.e(1, "gads:nativeads:media_content_aspect_ratio:enabled", Boolean.TRUE);

    /* renamed from: f  reason: collision with root package name */
    public static final zzaag<Integer> f5718f = zzaag.d(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzaag<Boolean> f0 = zzaag.e(1, "gads:interstitial:app_must_be_foreground:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> f1 = zzaag.e(1, "gads:gestures:hpk:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> f2 = zzaag.e(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.FALSE);
    public static final zzaag<Boolean> f3 = zzaag.e(1, "gads:nativeads:media_content_metadata:enabled", Boolean.TRUE);
    public static final zzaag<Integer> g = zzaag.d(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzaag<Boolean> g0 = zzaag.e(1, "gads:interstitial:foreground_report:enabled", Boolean.FALSE);
    public static final zzaag<String> g1 = zzaag.f(1, "gads:gestures:pk", "");
    public static final zzaag<Boolean> g2 = zzaag.e(1, "gad:interstitial_multi_window_method", Boolean.FALSE);
    public static final zzaag<Boolean> g3 = zzaag.e(1, "gads:ar_ads:enabled", Boolean.FALSE);
    public static final zzaag<Integer> h = zzaag.d(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final zzaag<Boolean> h0 = zzaag.e(1, "gads:webview:error_web_response:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> h1 = zzaag.e(1, "gads:gestures:bs:enabled", Boolean.TRUE);
    public static final zzaag<Integer> h2 = zzaag.d(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzaag<Boolean> h3 = zzaag.e(1, "gads:precache_pool:verbose_logging", Boolean.FALSE);
    public static final zzaag<Integer> i = zzaag.d(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final zzaag<Boolean> i0 = zzaag.e(1, "gads:webview:pause_interstitial:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> i1 = zzaag.e(1, "gads:gestures:check_initialization_thread:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> i2 = zzaag.e(1, "gads:clearcut_logging:enabled", Boolean.FALSE);
    public static final zzaag<Integer> i3 = zzaag.d(1, "gads:rewarded_precache_pool:count", 0);
    public static final zzaag<String> j = zzaag.f(1, "gads:video_exo_player:precache_exceptions", "");
    public static final zzaag<Boolean> j0 = zzaag.e(1, "gads:webviewgone:kill_process:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> j1 = zzaag.e(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> j2 = zzaag.e(1, "gads:clearcut_logging:write_to_file", Boolean.FALSE);
    public static final zzaag<Integer> j3 = zzaag.d(1, "gads:interstitial_precache_pool:count", 0);
    public static final zzaag<Integer> k = zzaag.d(1, "gads:video_exo_player:min_retry_count", -1);
    public static final zzaag<Boolean> k0 = zzaag.e(1, "gads:webviewgone:new_onshow:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> k1 = zzaag.e(1, "gads:gestures:init_new_thread:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> k2 = zzaag.e(1, "gad:publisher_testing:force_local_request:enabled", Boolean.TRUE);
    public static final zzaag<String> k3 = zzaag.f(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
    public static final zzaag<Boolean> l = zzaag.e(1, "gads:video_exo_player:fmp4_extractor_enabled", Boolean.FALSE);
    public static final zzaag<Boolean> l0 = zzaag.e(1, "gads:webview:pause_resume:enabled", Boolean.TRUE);
    public static final zzaag<Boolean> l1 = zzaag.e(1, "gads:gestures:pds:enabled", Boolean.TRUE);
    public static final zzaag<String> l2 = zzaag.f(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    public static final zzaag<String> l3 = zzaag.f(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
    public static final zzaag<Integer> m = zzaag.d(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzaag<String> m0 = zzaag.f(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
    public static final zzaag<Boolean> m1 = zzaag.e(1, "gads:gestures:las:enabled", Boolean.FALSE);
    public static final zzaag<String> m2 = zzaag.f(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    public static final zzaag<String> m3 = zzaag.f(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaag<Integer> n = zzaag.d(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzaag<Boolean> n0 = zzaag.e(1, "gads:rewarded:adapter_initialization_enabled", Boolean.FALSE);
    public static final zzaag<Boolean> n1 = zzaag.e(1, "gads:gestures:ns:enabled", Boolean.TRUE);
    public static final zzaag<Integer> n2 = zzaag.d(1, "gad:http_redirect_max_count:times", 8);
    public static final zzaag<String> n3 = zzaag.f(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaag<Integer> o = zzaag.d(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzaag<Boolean> o0 = zzaag.e(1, "gads:rewarded:ad_metadata_enabled", Boolean.FALSE);
    public static final zzaag<Boolean> o1 = zzaag.e(1, "gads:gestures:vdd:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> o2 = zzaag.e(1, "gads:omid:enabled", Boolean.TRUE);
    public static final zzaag<Integer> o3 = zzaag.d(1, "gads:rewarded_precache_pool:size", 1);
    public static final zzaag<Long> p = zzaag.k(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzaag<Boolean> p0 = zzaag.e(1, "gads:rewarded:ssv_custom_data_enabled", Boolean.TRUE);
    public static final zzaag<Boolean> p1 = zzaag.e(1, "gads:native:asset_view_touch_events", Boolean.FALSE);
    public static final zzaag<Integer> p2 = zzaag.d(1, "gads:omid:destroy_webview_delay", 1000);
    public static final zzaag<Integer> p3 = zzaag.d(1, "gads:interstitial_precache_pool:size", 1);
    public static final zzaag<Long> q = zzaag.k(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzaag<Long> q0 = zzaag.k(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzaag<Boolean> q1 = zzaag.e(1, "gads:native:set_touch_listener_on_asset_views", Boolean.TRUE);
    public static final zzaag<Integer> q2 = zzaag.d(1, "gads:app_open_beta:min_version", 99999999);
    public static final zzaag<Integer> q3 = zzaag.d(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
    public static final zzaag<Integer> r = zzaag.d(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzaag<Long> r0 = zzaag.k(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzaag<Boolean> r1 = zzaag.e(1, "gads:ais:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> r2 = zzaag.e(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.FALSE);
    public static final zzaag<Integer> r3 = zzaag.d(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
    public static final zzaag<String> s = zzaag.f(1, "gads:video:metric_frame_hash_times", "");
    public static final zzaag<Boolean> s0 = zzaag.e(1, "gads:adid_values_in_adrequest:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> s1 = zzaag.e(1, "gads:send_available_disk_space:enabled", Boolean.FALSE);
    public static final zzaag<String> s2 = zzaag.f(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    public static final zzaag<String> s3 = zzaag.f(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaag<Long> t = zzaag.k(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzaag<Long> t0 = zzaag.k(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzaag<String> t1 = zzaag.f(1, "gads:sdk_core_constants:caps", "");
    public static final zzaag<Boolean> t2 = zzaag.e(1, "gads:nonagon:banner:check_dp_size", Boolean.TRUE);
    public static final zzaag<String> t3 = zzaag.f(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaag<Boolean> u = zzaag.e(1, "gads:video:force_watermark", Boolean.FALSE);
    public static final zzaag<Boolean> u0 = zzaag.e(1, "gads:disable_adid_values_in_ms", Boolean.FALSE);
    public static final zzaag<String> u1 = zzaag.f(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzaag<Boolean> u2 = zzaag.e(1, "gads:nonagon:rewarded:load_multiple_ads", Boolean.TRUE);
    public static final zzaag<String> u3 = zzaag.f(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzaag<Long> v = zzaag.k(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzaag<Long> v0 = zzaag.k(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzaag<String> v1 = zzaag.f(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzaag<Boolean> v2 = zzaag.e(1, "gads:nonagon:return_no_fill_error_code", Boolean.FALSE);
    public static final zzaag<String> v3 = zzaag.f(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
    public static final zzaag<Boolean> w = zzaag.e(1, "gads:video:spinner:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> w0 = zzaag.e(1, "gads:custom_close_blocking:enabled", Boolean.FALSE);
    public static final zzaag<Integer> w1 = zzaag.d(1, "gads:native_video_load_timeout", 10);
    public static final zzaag<Boolean> w2 = zzaag.e(1, "gads:nonagon:continue_on_no_fill", Boolean.FALSE);
    public static final zzaag<Integer> w3 = zzaag.d(1, "gads:app_open_precache_pool:count", 0);
    public static final zzaag<Integer> x = zzaag.d(1, "gads:video:spinner:scale", 4);
    public static final zzaag<Boolean> x0 = zzaag.e(1, "gads:disabling_closable_area:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> x1 = zzaag.e(1, "gads:enable_native_media_aspect_ratio", Boolean.TRUE);
    public static final zzaag<Boolean> x2 = zzaag.e(1, "gads:nonagon:separate_timeout:enabled", Boolean.TRUE);
    public static final zzaag<String> x3 = zzaag.f(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzaag<Long> y = zzaag.k(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzaag<Boolean> y0 = zzaag.e(1, "gads:use_system_ui_for_fullscreen:enabled", Boolean.FALSE);
    public static final zzaag<Boolean> y1 = zzaag.e(1, "gads:native:media_content_main_image:enabled", Boolean.TRUE);
    public static final zzaag<Integer> y2 = zzaag.d(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final zzaag<Integer> y3 = zzaag.d(1, "gads:app_open_precache_pool:size", 1);
    public static final zzaag<Boolean> z = zzaag.e(1, "gads:video:aggressive_media_codec_release", Boolean.FALSE);
    public static final zzaag<Boolean> z0 = zzaag.e(1, "gads:ad_overlay:collect_cutout_info:enabled", Boolean.FALSE);
    public static final zzaag<String> z1 = zzaag.f(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzaag<Boolean> z2 = zzaag.e(1, "gads:nonagon:banner_recursive_renderer", Boolean.FALSE);
    public static final zzaag<Integer> z3 = zzaag.d(1, "gads:app_open_precache_pool:ad_time_limit", 14400);

    static {
        zzabx<Boolean> zzabx = zzacm.f5783c;
        zzaag.d(1, "gads:http_url_connection_factory:timeout_millis", 10000);
        zzaag.e(1, "gads:rsku:webviewgone:kill_process:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:rsku:webviewgone:new_onshow:enabled", Boolean.TRUE);
        zzaag.e(1, "gads:new_rewarded_ad:enabled", Boolean.TRUE);
        zzaag.k(1, "gads:rewarded:adapter_timeout_ms", 20000);
        zzaag.e(1, "gads:impression_optimization_enabled", Boolean.FALSE);
        zzaag.f(1, "gads:banner_ad_pool:schema", "customTargeting");
        zzaag.d(1, "gads:banner_ad_pool:max_queues", 3);
        zzaag.d(1, "gads:banner_ad_pool:max_pools", 3);
        zzaag.e(1, "gads:interstitial_ad_pool:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.FALSE);
        zzaag.f(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        zzaag.f(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        zzaag.d(1, "gads:interstitial_ad_pool:max_pools", 3);
        zzaag.d(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        zzaag.d(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        zzaag.f(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        zzaag.d(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        zzaag.d(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        zzaag.k(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
        zzaag.k(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
        zzaag.c(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
        zzaag.c(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
        zzaag.e(1, "gads:gen204_signals:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:initialization_csi_control:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:gestures:brt:enabled", Boolean.TRUE);
        zzaag.d(1, "gads:gestures:as2percentage", 0);
        zzwg.d().c(zzaag.f(1, "gads:sdk_core_constants:experiment_id", (String) null));
        zzaag.e(1, "gads:js_flags:disable_phenotype", Boolean.FALSE);
        zzaag.f(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        zzaag.d(1, "gads:omid:native_webview_load_timeout", 2000);
        zzaag.e(1, "gads:enable_store_active_view_state", Boolean.FALSE);
        zzaag.e(1, "gads:instream_ad:enabled", Boolean.TRUE);
        zzaag.e(1, "gads:auto_location_for_coarse_permission", Boolean.FALSE);
        zzaag.j(1, "gads:auto_location_for_coarse_permission:experiment_id");
        zzaag.j(1, "gads:auto_location_timeout:experiment_id");
        zzaag.k(1, "gads:auto_location_interval", -1);
        zzaag.j(1, "gads:auto_location_interval:experiment_id");
        zzaag.d(1, "gads:cache:ad_request_timeout_millis", 250);
        zzaag.d(1, "gads:cache:max_concurrent_downloads", 10);
        zzaag.k(1, "gads:cache:javascript_timeout_millis", 5000);
        zzaag.e(1, "gads:omid_1_3_activate:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:nonagon:banner:enabled", Boolean.FALSE);
        zzaag.f(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        zzaag.e(1, "gads:nonagon:app_open:enabled", Boolean.TRUE);
        zzaag.f(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
        zzaag.e(1, "gads:nonagon:interstitial:enabled", Boolean.FALSE);
        zzaag.f(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        zzaag.e(1, "gads:nonagon:rewardedvideo:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:nonagon:nativead:enabled", Boolean.FALSE);
        zzaag.f(1, "gads:nonagon:nativead:app_name", "(?!)");
        zzaag.e(1, "gads:nonagon:return_last_error_code", Boolean.FALSE);
        zzaag.e(1, "gads:nonagon:open_not_loaded_interstitial", Boolean.TRUE);
        zzaag.e(1, "gads:nonagon:service:enabled", Boolean.TRUE);
        zzaag.e(1, "gads:signals:doritos:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:signals:doritos:v2:immediate:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:signals:network_prediction:enabled", Boolean.FALSE);
        zzaag.e(1, "gads:attestation_token:enabled", Boolean.FALSE);
        zzabx<Boolean> zzabx2 = zzaco.f5786a;
    }

    public static void a(Context context) {
        zzbai.b(new l(context));
    }

    /* JADX WARNING: type inference failed for: r0v1, types: [com.google.android.gms.internal.ads.h, com.google.android.gms.internal.ads.zzadb] */
    public static void b(Context context, int i4, JSONObject jSONObject) {
        zzwg.c();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzacc.a(new h(zzwg.d(), edit, jSONObject));
        zzwg.d().a(edit, 1, jSONObject);
        zzwg.c();
        edit.commit();
    }

    public static List<String> d() {
        return zzwg.d().e();
    }

    public static List<String> e() {
        return zzwg.d().f();
    }
}
