package com.tempmail.m;

import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RadioButton;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Group;
import androidx.constraintlayout.widget.Guideline;
import androidx.databinding.ViewDataBinding;

/* compiled from: FragmentPremiumBinding */
public abstract class i0 extends ViewDataBinding {
    public final ConstraintLayout A;
    public final TextView A0;
    public final ConstraintLayout B;
    public final TextView B0;
    public final Guideline C;
    public final TextView C0;
    public final ConstraintLayout D;
    public final TextView D0;
    public final ImageView E;
    public final TextView E0;
    public final ImageView F;
    public final TextView F0;
    public final ImageView G;
    public final TextView G0;
    public final ImageView H;
    public final TextView H0;
    public final ImageView I;
    public final TextView I0;
    public final ImageView J;
    public final TextView J0;
    public final ImageView K;
    public final TextView K0;
    public final ImageView L;
    public final TextView L0;
    public final ImageView M;
    public final TextView M0;
    public final ImageView N;
    public final TextView N0;
    public final ImageView O;
    public final TextView O0;
    public final ImageView P;
    public final TextView P0;
    public final ImageView Q;
    public final TextView Q0;
    public final Guideline R;
    public final TextView R0;
    public final View S;
    public final TextView S0;
    public final View T;
    public final TextView T0;
    public final View U;
    public final TextView U0;
    public final View V;
    public final TextView V0;
    public final View W;
    public final TextView W0;
    public final View X;
    public final TextView X0;
    public final View Y;
    public final TextView Y0;
    public final Group Z;
    public final TextView Z0;
    public final RadioButton a0;
    public final TextView a1;
    public final RadioButton b0;
    public final TextView b1;
    public final RadioButton c0;
    public final TextView c1;
    public final RadioButton d0;
    public final TextView d1;
    public final RadioButton e0;
    public final TextView e1;
    public final Guideline f0;
    public final TextView f1;
    public final TextView g0;
    public final TextView g1;
    public final TextView h0;
    public final TextView h1;
    public final TextView i0;
    public final TextView i1;
    public final TextView j0;
    public final TextView j1;
    public final TextView k0;
    public final TextView l0;
    public final TextView m0;
    public final TextView n0;
    public final TextView o0;
    public final TextView p0;
    public final Button q;
    public final TextView q0;
    public final ConstraintLayout r;
    public final TextView r0;
    public final ConstraintLayout s;
    public final TextView s0;
    public final ConstraintLayout t;
    public final TextView t0;
    public final ConstraintLayout u;
    public final TextView u0;
    public final Button v;
    public final TextView v0;
    public final ConstraintLayout w;
    public final TextView w0;
    public final ConstraintLayout x;
    public final TextView x0;
    public final ConstraintLayout y;
    public final TextView y0;
    public final ConstraintLayout z;
    public final TextView z0;

    /* JADX INFO: super call moved to the top of the method (can break code semantics) */
    protected i0(Object obj, View view, int i, Button button, ConstraintLayout constraintLayout, ConstraintLayout constraintLayout2, ConstraintLayout constraintLayout3, ConstraintLayout constraintLayout4, Button button2, ConstraintLayout constraintLayout5, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, ConstraintLayout constraintLayout8, ConstraintLayout constraintLayout9, ConstraintLayout constraintLayout10, Guideline guideline, ConstraintLayout constraintLayout11, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, ImageView imageView7, ImageView imageView8, ImageView imageView9, ImageView imageView10, ImageView imageView11, ImageView imageView12, ImageView imageView13, Guideline guideline2, View view2, View view3, View view4, View view5, View view6, View view7, View view8, Group group, RadioButton radioButton, RadioButton radioButton2, RadioButton radioButton3, RadioButton radioButton4, RadioButton radioButton5, Guideline guideline3, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, TextView textView48, TextView textView49, TextView textView50, TextView textView51, TextView textView52, TextView textView53, TextView textView54, TextView textView55, TextView textView56) {
        super(obj, view, i);
        this.q = button;
        this.r = constraintLayout;
        this.s = constraintLayout2;
        this.t = constraintLayout3;
        this.u = constraintLayout4;
        this.v = button2;
        this.w = constraintLayout5;
        this.x = constraintLayout6;
        this.y = constraintLayout7;
        this.z = constraintLayout8;
        this.A = constraintLayout9;
        this.B = constraintLayout10;
        this.C = guideline;
        this.D = constraintLayout11;
        this.E = imageView;
        this.F = imageView2;
        this.G = imageView3;
        this.H = imageView4;
        this.I = imageView5;
        this.J = imageView6;
        this.K = imageView7;
        this.L = imageView8;
        this.M = imageView9;
        this.N = imageView10;
        this.O = imageView11;
        this.P = imageView12;
        this.Q = imageView13;
        this.R = guideline2;
        this.S = view2;
        this.T = view3;
        this.U = view4;
        this.V = view5;
        this.W = view6;
        this.X = view7;
        this.Y = view8;
        this.Z = group;
        this.a0 = radioButton;
        this.b0 = radioButton2;
        this.c0 = radioButton3;
        this.d0 = radioButton4;
        this.e0 = radioButton5;
        this.f0 = guideline3;
        this.g0 = textView;
        this.h0 = textView2;
        this.i0 = textView3;
        this.j0 = textView4;
        this.k0 = textView5;
        this.l0 = textView6;
        this.m0 = textView7;
        this.n0 = textView8;
        this.o0 = textView9;
        this.p0 = textView10;
        this.q0 = textView11;
        this.r0 = textView12;
        this.s0 = textView13;
        this.t0 = textView14;
        this.u0 = textView15;
        this.v0 = textView16;
        this.w0 = textView17;
        this.x0 = textView18;
        this.y0 = textView19;
        this.z0 = textView20;
        this.A0 = textView21;
        this.B0 = textView22;
        this.C0 = textView23;
        this.D0 = textView24;
        this.E0 = textView25;
        this.F0 = textView26;
        this.G0 = textView27;
        this.H0 = textView28;
        this.I0 = textView29;
        this.J0 = textView30;
        this.K0 = textView31;
        this.L0 = textView32;
        this.M0 = textView33;
        this.N0 = textView34;
        this.O0 = textView35;
        this.P0 = textView36;
        this.Q0 = textView37;
        this.R0 = textView38;
        this.S0 = textView39;
        this.T0 = textView40;
        this.U0 = textView41;
        this.V0 = textView42;
        this.W0 = textView43;
        this.X0 = textView44;
        this.Y0 = textView45;
        this.Z0 = textView46;
        this.a1 = textView47;
        this.b1 = textView48;
        this.c1 = textView49;
        this.d1 = textView50;
        this.e1 = textView51;
        this.f1 = textView52;
        this.g1 = textView53;
        this.h1 = textView54;
        this.i1 = textView55;
        this.j1 = textView56;
    }
}
